"""Pre-canned buffer + correction text per pattern.

Buffer lines are deterministic — they always play first so Plivo has
a stream of audio to fill the dead air while the correction LLM call
runs (or while the canned correction is selected).

For `contradiction`, the correction itself is generated by the LLM
because the item names vary; `fallback_template` is used only when
the LLM call fails or times out.

For `missing_tool_request`, the correction is fully canned — we
already know exactly what to say (we don't have the tool, here's a
human handoff).
"""

CANNED: dict = {
    "contradiction": {
        "buffer": "Sorry — let me make sure I got that right, just a moment...",
        "fallback_template": (
            "Just to confirm — you'd like a {final_item} pizza, "
            "no {removed_item} — is that right?"
        ),
    },
    "missing_tool_request": {
        "buffer": "Hmm, let me check on that for you...",
        "correction": (
            "Actually, I'm only set up to take new orders right now — "
            "but I can connect you with someone who can help with that. "
            "Would you like me to transfer you?"
        ),
    },
}


def fallback_correction(pattern_result: dict) -> str:
    """Deterministic correction when the LLM path fails.

    Heuristics from Mirror's evidence:
    - If `negated_item` present (secondary contradiction signal), use it
      as the removed item; final_item is the other detected item.
    - Otherwise, assume the LAST item mentioned is what the customer
      actually wants and the first is what they retracted.
    """
    pattern = pattern_result.get("pattern_name", "")
    evidence = pattern_result.get("evidence", {}) or {}

    if pattern == "contradiction":
        items = list(evidence.get("items_detected") or [])
        kept_hints = list(evidence.get("likely_kept_items") or [])
        removed_hints = list(evidence.get("likely_removed_items") or [])
        negated = evidence.get("negated_item")
        tmpl = CANNED["contradiction"]["fallback_template"]

        # Strongest signal: explicit classifier output.
        if kept_hints and removed_hints:
            return tmpl.format(
                final_item=kept_hints[-1], removed_item=removed_hints[0]
            )
        if kept_hints and not removed_hints:
            return f"Just to confirm — you'd like a {kept_hints[-1]} pizza — is that right?"
        if removed_hints and not kept_hints:
            return (
                f"Just to confirm — no {removed_hints[0]} on that, right? "
                "What would you like instead?"
            )

        if negated:
            kept = [i for i in items if i.lower() != negated.lower()]
            if kept:
                return tmpl.format(final_item=kept[-1], removed_item=negated)
            return (
                f"Just to confirm — no {negated} on that, right? "
                "What would you like instead?"
            )

        if len(items) >= 2:
            return tmpl.format(final_item=items[-1], removed_item=items[0])

        if len(items) == 1:
            return f"Just to confirm — you'd like a {items[0]} pizza — is that right?"

        return "Just to make sure I got that — could you say your order one more time?"

    if pattern == "missing_tool_request":
        return CANNED["missing_tool_request"]["correction"]

    return "Just to make sure I got that — could you say that one more time?"
