"""FailureReport schema."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class ReportStatus(str, Enum):
    PENDING = "pending"
    APPLIED = "applied"
    DISMISSED = "dismissed"
    FAILED = "failed"


@dataclass
class FailureReport:
    """Structured analysis of a single failed call.

    Generated by ``ReportGenerator`` when Mirror intervened during a
    call (or when the post-call analysis flags a slip Mirror's live
    pipeline missed). Persisted by a ``ReportSink``. Consumed by a
    ``Fixer`` to open a PR.
    """

    # Identity
    id: int | None = None                          # filled by sink on persist
    call_uuid: str = ""
    tenant_id: str | None = None

    # Diagnosis
    pattern_name: str = ""                         # e.g. "retracted_item", "third_party_preference"
    severity: str = "medium"                       # critical | high | medium | low
    summary: str = ""                              # one sentence — what went wrong from the caller's POV
    root_cause: str = ""                           # 2-3 sentences — WHY the agent failed
    proposed_fix_text: str = ""                    # 2-3 sentences — how to fix the agent prompt/code
    proposed_file: str = ""                        # relative path the fix would target
    suggested_diff: str = ""                       # a small diff or replacement snippet
    confidence: float = 0.5                        # 0-1 — how confident the report generator is

    # Lifecycle
    status: ReportStatus = ReportStatus.PENDING
    applied_pr_url: str | None = None
    applied_at: str | None = None
    dismissed_by: str | None = None
    dismissed_at: str | None = None
    last_error: str | None = None
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # Free-form for downstream tooling
    extras: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        d = {
            "id": self.id,
            "call_uuid": self.call_uuid,
            "tenant_id": self.tenant_id,
            "pattern_name": self.pattern_name,
            "severity": self.severity,
            "summary": self.summary,
            "root_cause": self.root_cause,
            "proposed_fix_text": self.proposed_fix_text,
            "proposed_file": self.proposed_file,
            "suggested_diff": self.suggested_diff,
            "confidence": self.confidence,
            "status": self.status.value if isinstance(self.status, ReportStatus) else str(self.status),
            "applied_pr_url": self.applied_pr_url,
            "applied_at": self.applied_at,
            "dismissed_by": self.dismissed_by,
            "dismissed_at": self.dismissed_at,
            "last_error": self.last_error,
            "created_at": self.created_at,
            "extras": self.extras,
        }
        return d


__all__ = ["FailureReport", "ReportStatus"]
